### ISSUE TITLE
Demo sites now working on Brave/Linux

### ISSUE THREAD

**Issue by johnmckinzie** [hay-kot/homebox#541]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Not sure

### What is the issue you are experiencing?

When I got to https://homebox.fly.dev/home, the screen comes up blank. I've attached the console log. 

```
DevTools failed to load source map: Could not load content for chrome-extension://blcdfhbibkkjpfdddnmnmhfgjlicebba/js/content_script.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://hnfanknocfeofbddgcijnmhnfnkdnaad/requestProvider.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
use-api.6d0295f2.js:3 200   https://homebox.fly.dev/api/v1/users/self   
use-server-events.0d5223dd.js:1 Mixed Content: The page at 'https://homebox.fly.dev/home' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://homebox.fly.dev/api/v1/ws/events'. This request has been blocked; this endpoint must be available over WSS.
h @ use-server-events.0d5223dd.js:1
k @ use-server-events.0d5223dd.js:1
setup @ default.c905bf19.js:1
Bt @ entry.16ceb39e.js:1
Df @ entry.16ceb39e.js:1
Nf @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
(anonymous) @ entry.16ceb39e.js:1
Promise.then (async)
registerDep @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
Qu @ entry.16ceb39e.js:1
process @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
Qu @ entry.16ceb39e.js:1
process @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
W @ entry.16ceb39e.js:1
mount @ entry.16ceb39e.js:1
Sd.t.mount @ entry.16ceb39e.js:1
Ol @ entry.16ceb39e.js:11
await in Ol (async)
(anonymous) @ entry.16ceb39e.js:11
entry.16ceb39e.js:1 DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at h (https://homebox.fly.dev/_nuxt/use-server-events.0d5223dd.js:1:1692)
    at k (https://homebox.fly.dev/_nuxt/use-server-events.0d5223dd.js:1:2158)
    at setup (https://homebox.fly.dev/_nuxt/default.c905bf19.js:1:41089)
    at Bt (https://homebox.fly.dev/_nuxt/entry.16ceb39e.js:1:13585)
    at Df (https://homebox.fly.dev/_nuxt/entry.16ceb39e.js:1:61348)
    at Nf (https://homebox.fly.dev/_nuxt/entry.16ceb39e.js:1:61133)
    at F (https://homebox.fly.dev/_nuxt/entry.16ceb39e.js:1:50466)
    at J (https://homebox.fly.dev/_nuxt/entry.16ceb39e.js:1:50358)
    at b (https://homebox.fly.dev/_nuxt/entry.16ceb39e.js:1:47261)
    at Eo.x [as fn] (https://homebox.fly.dev/_nuxt/entry.16ceb39e.js:1:51439)
Fu @ entry.16ceb39e.js:1
Dn @ entry.16ceb39e.js:1
Bt @ entry.16ceb39e.js:1
Df @ entry.16ceb39e.js:1
Nf @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
(anonymous) @ entry.16ceb39e.js:1
Promise.then (async)
registerDep @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
Qu @ entry.16ceb39e.js:1
process @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
Qu @ entry.16ceb39e.js:1
process @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
x @ entry.16ceb39e.js:1
run @ entry.16ceb39e.js:1
h.update @ entry.16ceb39e.js:1
ee @ entry.16ceb39e.js:1
F @ entry.16ceb39e.js:1
J @ entry.16ceb39e.js:1
b @ entry.16ceb39e.js:1
W @ entry.16ceb39e.js:1
mount @ entry.16ceb39e.js:1
Sd.t.mount @ entry.16ceb39e.js:1
Ol @ entry.16ceb39e.js:11
await in Ol (async)
(anonymous) @ entry.16ceb39e.js:11
use-api.6d0295f2.js:3 200   https://homebox.fly.dev/api/v1/groups   
```

### How can the maintainer reproduce the issue?

Try viewing the demo site with Brave ([Version 1.57.47 Chromium: 116.0.5845.96 (Official Build) (64-bit)](https://brave.com/latest/)) on Linux (Pop!_OS 22.04 LTS).

### Deployment

Other

**Comment by gucheen** [comment]
since nightly version adds websocket related functions, but connect to an insecure websocket (ws://) will be failed under https

**Comment by johnmckinzie** [comment]
@gucheen thanks for the response. I'm trying to figure out a way for it not to redirect HTTP to HTTPS.

**Comment by hay-kot** [comment]
Shoot. I Wrote this bug like 6 months ago on anther project. The fix is easy enough, basically we need to check the protocol of the current connection before trying to establish a websocket connection. 

Will get a fix in this weekend. Thanks for reporting!
